# Generated by Django 2.2.26 on 2023-01-11 14:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
            bases=('allocationapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
