# Generated by Django 4.1.3 on 2023-02-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': (('can_access_admin_pages', 'Can access all admin pages.'),), 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'permissions': (('can_access_graduate_pages', 'Can access all graduate pages.'),), 'verbose_name_plural': 'Graduates'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': (('can_access_manager_pages', 'Can access all manager pages.'),), 'verbose_name_plural': 'Managers'},
        ),
    ]
