# Generated by Django 3.1.6 on 2023-01-11 15:53

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allocationapp.customuser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('allocationapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminID',
            new_name='adminId',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Manager'), (2, 'Graduate'), (3, 'HR_rep')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('skill_1', 'Maths'), ('skill_2', 'Data Science'), ('skill_3', 'Programming'), ('skill_4', 'Critical Thinking'), ('skill_5', 'Statistics')], max_length=39)),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('technologies_1', 'Python'), ('technologies_2', 'Java'), ('technologies_3', 'C/C++'), ('technologies_4', 'Haskell'), ('technologies_5', 'R')], max_length=74)),
                ('capacity', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocationapp.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('gradId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='allocationapp.graduate')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='allocationapp.team')),
            ],
        ),
        migrations.AddField(
            model_name='graduate',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='allocationapp.team'),
        ),
    ]
