# Generated by Django 4.1.3 on 2023-02-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0002_alter_admin_options_alter_graduate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name_plural': 'Graduates'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name_plural': 'Managers'},
        ),
    ]
