# Generated by Django 3.1.6 on 2023-01-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0003_auto_20230111_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name_plural': 'Graduates'},
        ),
    ]
