# Generated by Django 4.1.6 on 2023-02-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0003_alter_admin_options_alter_graduate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_allocated', models.BooleanField(default=False)),
            ],
        ),
    ]
