# Generated by Django 3.1.6 on 2023-01-17 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0004_auto_20230111_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='gradId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
